import {useCallback,useEffect,useRef,useState} from 'react';
import {pickQuestions} from '../data/questions';import {speedBonus} from './scoring';import type{Difficulty,ElementKey,Phase,Question}from'../types';import type{Sound}from'../audio/useSynthAudio';
export function useGame(play:(s:Sound)=>void){const [phase,setPhase]=useState<Phase>('idle'),[difficulty,setDifficulty]=useState<Difficulty>('easy'),[round,setRound]=useState(0),[score,setScore]=useState(0),[set,setSet]=useState<Question[]>([]),[lit,setLit]=useState<ElementKey|null>(null),[inputCount,setInputCount]=useState(0),[lastGain,setLastGain]=useState(0),[quizCorrect,setQuizCorrect]=useState<boolean|null>(null);const startAt=useRef(0),token=useRef(0);const q=set[round];
 const later=useCallback((fn:()=>void,ms:number)=>{const t=token.current;window.setTimeout(()=>{if(t===token.current)fn()},ms)},[]);
 const showSequence=useCallback((question:Question)=>{setPhase('memorize');let i=0;const step=()=>{if(i>=question.sequence.length){setLit(null);later(()=>{startAt.current=performance.now();setPhase('input')},300);return}setLit(question.sequence[i]);play('memory');later(()=>{setLit(null);i++;later(step,230)},540)};later(step,450)},[later,play]);
 const chooseDifficulty=(d:Difficulty)=>{token.current++;setDifficulty(d);setSet(pickQuestions(d));setRound(0);setScore(0);setPhase('ready')};
 // Keep selection and shown question identical.
 useEffect(()=>{if(phase==='ready'&&set[0]){token.current++;later(()=>showSequence(set[0]),650)}},[phase,set,later,showSequence]);
 const press=useCallback((key:ElementKey)=>{if(phase!=='input'||!q)return;play('press');setLit(key);later(()=>setLit(null),130);if(key!==q.sequence[inputCount]){setPhase('inputFailure');setLastGain(0);play('failure');later(()=>{setInputCount(0);showSequence(q)},950);return}const next=inputCount+1;setInputCount(next);if(next===q.sequence.length){const gain=100+speedBonus(performance.now()-startAt.current);setLastGain(gain);setScore(s=>s+gain);setPhase('inputSuccess');play('success');later(()=>setPhase('quiz'),850)}},[phase,q,inputCount,later,play,showSequence]);
 const answer=(index:number)=>{if(phase!=='quiz'||!q)return;const ok=q.choices[index].formula===q.product.formula;setQuizCorrect(ok);setLastGain(g=>g+(ok?100:0));if(ok)setScore(s=>s+100);setPhase('quizResult');play(ok?'success':'failure');later(()=>{if(round===2){setPhase('gameResult');play('result')}else{setPhase('roundTransition');later(()=>{setRound(r=>r+1);setInputCount(0);setQuizCorrect(null);showSequence(set[round+1])},650)}},1100)};
 const reset=()=>{token.current++;setPhase('idle');setRound(0);setScore(0);setInputCount(0);setLit(null)};return{phase,difficulty,round,score,q,lit,inputCount,lastGain,quizCorrect,start:()=>setPhase('difficultySelect'),chooseDifficulty,press,answer,reset};}
